package com.vintage.entity;

import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_no
     *
     * @mbggenerated
     */
    private String bookNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.class_no
     *
     * @mbggenerated
     */
    private String classNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbggenerated
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author_name
     *
     * @mbggenerated
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publishing_name
     *
     * @mbggenerated
     */
    private String publishingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publishing_no
     *
     * @mbggenerated
     */
    private String publishingNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publishing_date
     *
     * @mbggenerated
     */
    private Date publishingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.shop_date
     *
     * @mbggenerated
     */
    private Date shopDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.shop_num
     *
     * @mbggenerated
     */
    private Short shopNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_no
     *
     * @return the value of book.book_no
     *
     * @mbggenerated
     */
    public String getBookNo() {
        return bookNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_no
     *
     * @param bookNo the value for book.book_no
     *
     * @mbggenerated
     */
    public void setBookNo(String bookNo) {
        this.bookNo = bookNo == null ? null : bookNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.class_no
     *
     * @return the value of book.class_no
     *
     * @mbggenerated
     */
    public String getClassNo() {
        return classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.class_no
     *
     * @param classNo the value for book.class_no
     *
     * @mbggenerated
     */
    public void setClassNo(String classNo) {
        this.classNo = classNo == null ? null : classNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbggenerated
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbggenerated
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author_name
     *
     * @return the value of book.author_name
     *
     * @mbggenerated
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author_name
     *
     * @param authorName the value for book.author_name
     *
     * @mbggenerated
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName == null ? null : authorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publishing_name
     *
     * @return the value of book.publishing_name
     *
     * @mbggenerated
     */
    public String getPublishingName() {
        return publishingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publishing_name
     *
     * @param publishingName the value for book.publishing_name
     *
     * @mbggenerated
     */
    public void setPublishingName(String publishingName) {
        this.publishingName = publishingName == null ? null : publishingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publishing_no
     *
     * @return the value of book.publishing_no
     *
     * @mbggenerated
     */
    public String getPublishingNo() {
        return publishingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publishing_no
     *
     * @param publishingNo the value for book.publishing_no
     *
     * @mbggenerated
     */
    public void setPublishingNo(String publishingNo) {
        this.publishingNo = publishingNo == null ? null : publishingNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publishing_date
     *
     * @return the value of book.publishing_date
     *
     * @mbggenerated
     */
    public Date getPublishingDate() {
        return publishingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publishing_date
     *
     * @param publishingDate the value for book.publishing_date
     *
     * @mbggenerated
     */
    public void setPublishingDate(Date publishingDate) {
        this.publishingDate = publishingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.shop_date
     *
     * @return the value of book.shop_date
     *
     * @mbggenerated
     */
    public Date getShopDate() {
        return shopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.shop_date
     *
     * @param shopDate the value for book.shop_date
     *
     * @mbggenerated
     */
    public void setShopDate(Date shopDate) {
        this.shopDate = shopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.shop_num
     *
     * @return the value of book.shop_num
     *
     * @mbggenerated
     */
    public Short getShopNum() {
        return shopNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.shop_num
     *
     * @param shopNum the value for book.shop_num
     *
     * @mbggenerated
     */
    public void setShopNum(Short shopNum) {
        this.shopNum = shopNum;
    }
}