package com.vintage.entity;

import java.math.BigDecimal;
import java.util.Date;

public class LossesDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.losses_detail_id
     *
     * @mbggenerated
     */
    private String lossesDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.losses_fee_type
     *
     * @mbggenerated
     */
    private Integer lossesFeeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.losses_mode
     *
     * @mbggenerated
     */
    private Byte lossesMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.losses_amount
     *
     * @mbggenerated
     */
    private BigDecimal lossesAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.losses_date
     *
     * @mbggenerated
     */
    private Date lossesDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.payee_member_id
     *
     * @mbggenerated
     */
    private String payeeMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.payee_name
     *
     * @mbggenerated
     */
    private String payeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.payer_member_id
     *
     * @mbggenerated
     */
    private String payerMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.payer_name
     *
     * @mbggenerated
     */
    private String payerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.payment_mode
     *
     * @mbggenerated
     */
    private Byte paymentMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.is_auto_balance
     *
     * @mbggenerated
     */
    private String isAutoBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.is_immediately_balance
     *
     * @mbggenerated
     */
    private Boolean isImmediatelyBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.trade_bill_id
     *
     * @mbggenerated
     */
    private String tradeBillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.trade_bill_no
     *
     * @mbggenerated
     */
    private String tradeBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.trade_bill_type
     *
     * @mbggenerated
     */
    private Byte tradeBillType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.original_way_bill_id
     *
     * @mbggenerated
     */
    private String originalWayBillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.is_supplement_bill
     *
     * @mbggenerated
     */
    private String isSupplementBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.is_month_settle
     *
     * @mbggenerated
     */
    private Boolean isMonthSettle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.delete_flg
     *
     * @mbggenerated
     */
    private String deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.creater_id
     *
     * @mbggenerated
     */
    private String createrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.updater_id
     *
     * @mbggenerated
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.trade_bill_create_time
     *
     * @mbggenerated
     */
    private Date tradeBillCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.original_way_bill_no
     *
     * @mbggenerated
     */
    private String originalWayBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.latest_time
     *
     * @mbggenerated
     */
    private Date latestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.payee_balance_status
     *
     * @mbggenerated
     */
    private Byte payeeBalanceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.already_income_amount
     *
     * @mbggenerated
     */
    private BigDecimal alreadyIncomeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.already_pay_amount
     *
     * @mbggenerated
     */
    private BigDecimal alreadyPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.losses_status
     *
     * @mbggenerated
     */
    private Byte lossesStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.original_fee_id
     *
     * @mbggenerated
     */
    private String originalFeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.fee_serial_no
     *
     * @mbggenerated
     */
    private String feeSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losses_detail.trade_serial_no
     *
     * @mbggenerated
     */
    private String tradeSerialNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.losses_detail_id
     *
     * @return the value of losses_detail.losses_detail_id
     *
     * @mbggenerated
     */
    public String getLossesDetailId() {
        return lossesDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.losses_detail_id
     *
     * @param lossesDetailId the value for losses_detail.losses_detail_id
     *
     * @mbggenerated
     */
    public void setLossesDetailId(String lossesDetailId) {
        this.lossesDetailId = lossesDetailId == null ? null : lossesDetailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.losses_fee_type
     *
     * @return the value of losses_detail.losses_fee_type
     *
     * @mbggenerated
     */
    public Integer getLossesFeeType() {
        return lossesFeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.losses_fee_type
     *
     * @param lossesFeeType the value for losses_detail.losses_fee_type
     *
     * @mbggenerated
     */
    public void setLossesFeeType(Integer lossesFeeType) {
        this.lossesFeeType = lossesFeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.losses_mode
     *
     * @return the value of losses_detail.losses_mode
     *
     * @mbggenerated
     */
    public Byte getLossesMode() {
        return lossesMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.losses_mode
     *
     * @param lossesMode the value for losses_detail.losses_mode
     *
     * @mbggenerated
     */
    public void setLossesMode(Byte lossesMode) {
        this.lossesMode = lossesMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.losses_amount
     *
     * @return the value of losses_detail.losses_amount
     *
     * @mbggenerated
     */
    public BigDecimal getLossesAmount() {
        return lossesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.losses_amount
     *
     * @param lossesAmount the value for losses_detail.losses_amount
     *
     * @mbggenerated
     */
    public void setLossesAmount(BigDecimal lossesAmount) {
        this.lossesAmount = lossesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.losses_date
     *
     * @return the value of losses_detail.losses_date
     *
     * @mbggenerated
     */
    public Date getLossesDate() {
        return lossesDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.losses_date
     *
     * @param lossesDate the value for losses_detail.losses_date
     *
     * @mbggenerated
     */
    public void setLossesDate(Date lossesDate) {
        this.lossesDate = lossesDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.payee_member_id
     *
     * @return the value of losses_detail.payee_member_id
     *
     * @mbggenerated
     */
    public String getPayeeMemberId() {
        return payeeMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.payee_member_id
     *
     * @param payeeMemberId the value for losses_detail.payee_member_id
     *
     * @mbggenerated
     */
    public void setPayeeMemberId(String payeeMemberId) {
        this.payeeMemberId = payeeMemberId == null ? null : payeeMemberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.payee_name
     *
     * @return the value of losses_detail.payee_name
     *
     * @mbggenerated
     */
    public String getPayeeName() {
        return payeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.payee_name
     *
     * @param payeeName the value for losses_detail.payee_name
     *
     * @mbggenerated
     */
    public void setPayeeName(String payeeName) {
        this.payeeName = payeeName == null ? null : payeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.payer_member_id
     *
     * @return the value of losses_detail.payer_member_id
     *
     * @mbggenerated
     */
    public String getPayerMemberId() {
        return payerMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.payer_member_id
     *
     * @param payerMemberId the value for losses_detail.payer_member_id
     *
     * @mbggenerated
     */
    public void setPayerMemberId(String payerMemberId) {
        this.payerMemberId = payerMemberId == null ? null : payerMemberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.payer_name
     *
     * @return the value of losses_detail.payer_name
     *
     * @mbggenerated
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.payer_name
     *
     * @param payerName the value for losses_detail.payer_name
     *
     * @mbggenerated
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName == null ? null : payerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.payment_mode
     *
     * @return the value of losses_detail.payment_mode
     *
     * @mbggenerated
     */
    public Byte getPaymentMode() {
        return paymentMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.payment_mode
     *
     * @param paymentMode the value for losses_detail.payment_mode
     *
     * @mbggenerated
     */
    public void setPaymentMode(Byte paymentMode) {
        this.paymentMode = paymentMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.is_auto_balance
     *
     * @return the value of losses_detail.is_auto_balance
     *
     * @mbggenerated
     */
    public String getIsAutoBalance() {
        return isAutoBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.is_auto_balance
     *
     * @param isAutoBalance the value for losses_detail.is_auto_balance
     *
     * @mbggenerated
     */
    public void setIsAutoBalance(String isAutoBalance) {
        this.isAutoBalance = isAutoBalance == null ? null : isAutoBalance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.is_immediately_balance
     *
     * @return the value of losses_detail.is_immediately_balance
     *
     * @mbggenerated
     */
    public Boolean getIsImmediatelyBalance() {
        return isImmediatelyBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.is_immediately_balance
     *
     * @param isImmediatelyBalance the value for losses_detail.is_immediately_balance
     *
     * @mbggenerated
     */
    public void setIsImmediatelyBalance(Boolean isImmediatelyBalance) {
        this.isImmediatelyBalance = isImmediatelyBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.trade_bill_id
     *
     * @return the value of losses_detail.trade_bill_id
     *
     * @mbggenerated
     */
    public String getTradeBillId() {
        return tradeBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.trade_bill_id
     *
     * @param tradeBillId the value for losses_detail.trade_bill_id
     *
     * @mbggenerated
     */
    public void setTradeBillId(String tradeBillId) {
        this.tradeBillId = tradeBillId == null ? null : tradeBillId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.trade_bill_no
     *
     * @return the value of losses_detail.trade_bill_no
     *
     * @mbggenerated
     */
    public String getTradeBillNo() {
        return tradeBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.trade_bill_no
     *
     * @param tradeBillNo the value for losses_detail.trade_bill_no
     *
     * @mbggenerated
     */
    public void setTradeBillNo(String tradeBillNo) {
        this.tradeBillNo = tradeBillNo == null ? null : tradeBillNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.trade_bill_type
     *
     * @return the value of losses_detail.trade_bill_type
     *
     * @mbggenerated
     */
    public Byte getTradeBillType() {
        return tradeBillType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.trade_bill_type
     *
     * @param tradeBillType the value for losses_detail.trade_bill_type
     *
     * @mbggenerated
     */
    public void setTradeBillType(Byte tradeBillType) {
        this.tradeBillType = tradeBillType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.original_way_bill_id
     *
     * @return the value of losses_detail.original_way_bill_id
     *
     * @mbggenerated
     */
    public String getOriginalWayBillId() {
        return originalWayBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.original_way_bill_id
     *
     * @param originalWayBillId the value for losses_detail.original_way_bill_id
     *
     * @mbggenerated
     */
    public void setOriginalWayBillId(String originalWayBillId) {
        this.originalWayBillId = originalWayBillId == null ? null : originalWayBillId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.is_supplement_bill
     *
     * @return the value of losses_detail.is_supplement_bill
     *
     * @mbggenerated
     */
    public String getIsSupplementBill() {
        return isSupplementBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.is_supplement_bill
     *
     * @param isSupplementBill the value for losses_detail.is_supplement_bill
     *
     * @mbggenerated
     */
    public void setIsSupplementBill(String isSupplementBill) {
        this.isSupplementBill = isSupplementBill == null ? null : isSupplementBill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.is_month_settle
     *
     * @return the value of losses_detail.is_month_settle
     *
     * @mbggenerated
     */
    public Boolean getIsMonthSettle() {
        return isMonthSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.is_month_settle
     *
     * @param isMonthSettle the value for losses_detail.is_month_settle
     *
     * @mbggenerated
     */
    public void setIsMonthSettle(Boolean isMonthSettle) {
        this.isMonthSettle = isMonthSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.delete_flg
     *
     * @return the value of losses_detail.delete_flg
     *
     * @mbggenerated
     */
    public String getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.delete_flg
     *
     * @param deleteFlg the value for losses_detail.delete_flg
     *
     * @mbggenerated
     */
    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg == null ? null : deleteFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.creater_id
     *
     * @return the value of losses_detail.creater_id
     *
     * @mbggenerated
     */
    public String getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.creater_id
     *
     * @param createrId the value for losses_detail.creater_id
     *
     * @mbggenerated
     */
    public void setCreaterId(String createrId) {
        this.createrId = createrId == null ? null : createrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.create_time
     *
     * @return the value of losses_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.create_time
     *
     * @param createTime the value for losses_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.updater_id
     *
     * @return the value of losses_detail.updater_id
     *
     * @mbggenerated
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.updater_id
     *
     * @param updaterId the value for losses_detail.updater_id
     *
     * @mbggenerated
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.update_time
     *
     * @return the value of losses_detail.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.update_time
     *
     * @param updateTime the value for losses_detail.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.trade_bill_create_time
     *
     * @return the value of losses_detail.trade_bill_create_time
     *
     * @mbggenerated
     */
    public Date getTradeBillCreateTime() {
        return tradeBillCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.trade_bill_create_time
     *
     * @param tradeBillCreateTime the value for losses_detail.trade_bill_create_time
     *
     * @mbggenerated
     */
    public void setTradeBillCreateTime(Date tradeBillCreateTime) {
        this.tradeBillCreateTime = tradeBillCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.original_way_bill_no
     *
     * @return the value of losses_detail.original_way_bill_no
     *
     * @mbggenerated
     */
    public String getOriginalWayBillNo() {
        return originalWayBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.original_way_bill_no
     *
     * @param originalWayBillNo the value for losses_detail.original_way_bill_no
     *
     * @mbggenerated
     */
    public void setOriginalWayBillNo(String originalWayBillNo) {
        this.originalWayBillNo = originalWayBillNo == null ? null : originalWayBillNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.latest_time
     *
     * @return the value of losses_detail.latest_time
     *
     * @mbggenerated
     */
    public Date getLatestTime() {
        return latestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.latest_time
     *
     * @param latestTime the value for losses_detail.latest_time
     *
     * @mbggenerated
     */
    public void setLatestTime(Date latestTime) {
        this.latestTime = latestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.payee_balance_status
     *
     * @return the value of losses_detail.payee_balance_status
     *
     * @mbggenerated
     */
    public Byte getPayeeBalanceStatus() {
        return payeeBalanceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.payee_balance_status
     *
     * @param payeeBalanceStatus the value for losses_detail.payee_balance_status
     *
     * @mbggenerated
     */
    public void setPayeeBalanceStatus(Byte payeeBalanceStatus) {
        this.payeeBalanceStatus = payeeBalanceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.already_income_amount
     *
     * @return the value of losses_detail.already_income_amount
     *
     * @mbggenerated
     */
    public BigDecimal getAlreadyIncomeAmount() {
        return alreadyIncomeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.already_income_amount
     *
     * @param alreadyIncomeAmount the value for losses_detail.already_income_amount
     *
     * @mbggenerated
     */
    public void setAlreadyIncomeAmount(BigDecimal alreadyIncomeAmount) {
        this.alreadyIncomeAmount = alreadyIncomeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.already_pay_amount
     *
     * @return the value of losses_detail.already_pay_amount
     *
     * @mbggenerated
     */
    public BigDecimal getAlreadyPayAmount() {
        return alreadyPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.already_pay_amount
     *
     * @param alreadyPayAmount the value for losses_detail.already_pay_amount
     *
     * @mbggenerated
     */
    public void setAlreadyPayAmount(BigDecimal alreadyPayAmount) {
        this.alreadyPayAmount = alreadyPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.losses_status
     *
     * @return the value of losses_detail.losses_status
     *
     * @mbggenerated
     */
    public Byte getLossesStatus() {
        return lossesStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.losses_status
     *
     * @param lossesStatus the value for losses_detail.losses_status
     *
     * @mbggenerated
     */
    public void setLossesStatus(Byte lossesStatus) {
        this.lossesStatus = lossesStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.original_fee_id
     *
     * @return the value of losses_detail.original_fee_id
     *
     * @mbggenerated
     */
    public String getOriginalFeeId() {
        return originalFeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.original_fee_id
     *
     * @param originalFeeId the value for losses_detail.original_fee_id
     *
     * @mbggenerated
     */
    public void setOriginalFeeId(String originalFeeId) {
        this.originalFeeId = originalFeeId == null ? null : originalFeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.remark
     *
     * @return the value of losses_detail.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.remark
     *
     * @param remark the value for losses_detail.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.fee_serial_no
     *
     * @return the value of losses_detail.fee_serial_no
     *
     * @mbggenerated
     */
    public String getFeeSerialNo() {
        return feeSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.fee_serial_no
     *
     * @param feeSerialNo the value for losses_detail.fee_serial_no
     *
     * @mbggenerated
     */
    public void setFeeSerialNo(String feeSerialNo) {
        this.feeSerialNo = feeSerialNo == null ? null : feeSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losses_detail.trade_serial_no
     *
     * @return the value of losses_detail.trade_serial_no
     *
     * @mbggenerated
     */
    public String getTradeSerialNo() {
        return tradeSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losses_detail.trade_serial_no
     *
     * @param tradeSerialNo the value for losses_detail.trade_serial_no
     *
     * @mbggenerated
     */
    public void setTradeSerialNo(String tradeSerialNo) {
        this.tradeSerialNo = tradeSerialNo == null ? null : tradeSerialNo.trim();
    }
}