package com.vintage.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LossesDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    public LossesDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andLossesDetailIdIsNull() {
            addCriterion("losses_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andLossesDetailIdIsNotNull() {
            addCriterion("losses_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andLossesDetailIdEqualTo(String value) {
            addCriterion("losses_detail_id =", value, "lossesDetailId");
            return (Criteria) this;
        }

        public Criteria andLossesDetailIdNotEqualTo(String value) {
            addCriterion("losses_detail_id <>", value, "lossesDetailId");
            return (Criteria) this;
        }

        public Criteria andLossesDetailIdGreaterThan(String value) {
            addCriterion("losses_detail_id >", value, "lossesDetailId");
            return (Criteria) this;
        }

        public Criteria andLossesDetailIdGreaterThanOrEqualTo(String value) {
            addCriterion("losses_detail_id >=", value, "lossesDetailId");
            return (Criteria) this;
        }

        public Criteria andLossesDetailIdLessThan(String value) {
            addCriterion("losses_detail_id <", value, "lossesDetailId");
            return (Criteria) this;
        }

        public Criteria andLossesDetailIdLessThanOrEqualTo(String value) {
            addCriterion("losses_detail_id <=", value, "lossesDetailId");
            return (Criteria) this;
        }

        public Criteria andLossesDetailIdLike(String value) {
            addCriterion("losses_detail_id like", value, "lossesDetailId");
            return (Criteria) this;
        }

        public Criteria andLossesDetailIdNotLike(String value) {
            addCriterion("losses_detail_id not like", value, "lossesDetailId");
            return (Criteria) this;
        }

        public Criteria andLossesDetailIdIn(List<String> values) {
            addCriterion("losses_detail_id in", values, "lossesDetailId");
            return (Criteria) this;
        }

        public Criteria andLossesDetailIdNotIn(List<String> values) {
            addCriterion("losses_detail_id not in", values, "lossesDetailId");
            return (Criteria) this;
        }

        public Criteria andLossesDetailIdBetween(String value1, String value2) {
            addCriterion("losses_detail_id between", value1, value2, "lossesDetailId");
            return (Criteria) this;
        }

        public Criteria andLossesDetailIdNotBetween(String value1, String value2) {
            addCriterion("losses_detail_id not between", value1, value2, "lossesDetailId");
            return (Criteria) this;
        }

        public Criteria andLossesFeeTypeIsNull() {
            addCriterion("losses_fee_type is null");
            return (Criteria) this;
        }

        public Criteria andLossesFeeTypeIsNotNull() {
            addCriterion("losses_fee_type is not null");
            return (Criteria) this;
        }

        public Criteria andLossesFeeTypeEqualTo(Integer value) {
            addCriterion("losses_fee_type =", value, "lossesFeeType");
            return (Criteria) this;
        }

        public Criteria andLossesFeeTypeNotEqualTo(Integer value) {
            addCriterion("losses_fee_type <>", value, "lossesFeeType");
            return (Criteria) this;
        }

        public Criteria andLossesFeeTypeGreaterThan(Integer value) {
            addCriterion("losses_fee_type >", value, "lossesFeeType");
            return (Criteria) this;
        }

        public Criteria andLossesFeeTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("losses_fee_type >=", value, "lossesFeeType");
            return (Criteria) this;
        }

        public Criteria andLossesFeeTypeLessThan(Integer value) {
            addCriterion("losses_fee_type <", value, "lossesFeeType");
            return (Criteria) this;
        }

        public Criteria andLossesFeeTypeLessThanOrEqualTo(Integer value) {
            addCriterion("losses_fee_type <=", value, "lossesFeeType");
            return (Criteria) this;
        }

        public Criteria andLossesFeeTypeIn(List<Integer> values) {
            addCriterion("losses_fee_type in", values, "lossesFeeType");
            return (Criteria) this;
        }

        public Criteria andLossesFeeTypeNotIn(List<Integer> values) {
            addCriterion("losses_fee_type not in", values, "lossesFeeType");
            return (Criteria) this;
        }

        public Criteria andLossesFeeTypeBetween(Integer value1, Integer value2) {
            addCriterion("losses_fee_type between", value1, value2, "lossesFeeType");
            return (Criteria) this;
        }

        public Criteria andLossesFeeTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("losses_fee_type not between", value1, value2, "lossesFeeType");
            return (Criteria) this;
        }

        public Criteria andLossesModeIsNull() {
            addCriterion("losses_mode is null");
            return (Criteria) this;
        }

        public Criteria andLossesModeIsNotNull() {
            addCriterion("losses_mode is not null");
            return (Criteria) this;
        }

        public Criteria andLossesModeEqualTo(Byte value) {
            addCriterion("losses_mode =", value, "lossesMode");
            return (Criteria) this;
        }

        public Criteria andLossesModeNotEqualTo(Byte value) {
            addCriterion("losses_mode <>", value, "lossesMode");
            return (Criteria) this;
        }

        public Criteria andLossesModeGreaterThan(Byte value) {
            addCriterion("losses_mode >", value, "lossesMode");
            return (Criteria) this;
        }

        public Criteria andLossesModeGreaterThanOrEqualTo(Byte value) {
            addCriterion("losses_mode >=", value, "lossesMode");
            return (Criteria) this;
        }

        public Criteria andLossesModeLessThan(Byte value) {
            addCriterion("losses_mode <", value, "lossesMode");
            return (Criteria) this;
        }

        public Criteria andLossesModeLessThanOrEqualTo(Byte value) {
            addCriterion("losses_mode <=", value, "lossesMode");
            return (Criteria) this;
        }

        public Criteria andLossesModeIn(List<Byte> values) {
            addCriterion("losses_mode in", values, "lossesMode");
            return (Criteria) this;
        }

        public Criteria andLossesModeNotIn(List<Byte> values) {
            addCriterion("losses_mode not in", values, "lossesMode");
            return (Criteria) this;
        }

        public Criteria andLossesModeBetween(Byte value1, Byte value2) {
            addCriterion("losses_mode between", value1, value2, "lossesMode");
            return (Criteria) this;
        }

        public Criteria andLossesModeNotBetween(Byte value1, Byte value2) {
            addCriterion("losses_mode not between", value1, value2, "lossesMode");
            return (Criteria) this;
        }

        public Criteria andLossesAmountIsNull() {
            addCriterion("losses_amount is null");
            return (Criteria) this;
        }

        public Criteria andLossesAmountIsNotNull() {
            addCriterion("losses_amount is not null");
            return (Criteria) this;
        }

        public Criteria andLossesAmountEqualTo(BigDecimal value) {
            addCriterion("losses_amount =", value, "lossesAmount");
            return (Criteria) this;
        }

        public Criteria andLossesAmountNotEqualTo(BigDecimal value) {
            addCriterion("losses_amount <>", value, "lossesAmount");
            return (Criteria) this;
        }

        public Criteria andLossesAmountGreaterThan(BigDecimal value) {
            addCriterion("losses_amount >", value, "lossesAmount");
            return (Criteria) this;
        }

        public Criteria andLossesAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("losses_amount >=", value, "lossesAmount");
            return (Criteria) this;
        }

        public Criteria andLossesAmountLessThan(BigDecimal value) {
            addCriterion("losses_amount <", value, "lossesAmount");
            return (Criteria) this;
        }

        public Criteria andLossesAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("losses_amount <=", value, "lossesAmount");
            return (Criteria) this;
        }

        public Criteria andLossesAmountIn(List<BigDecimal> values) {
            addCriterion("losses_amount in", values, "lossesAmount");
            return (Criteria) this;
        }

        public Criteria andLossesAmountNotIn(List<BigDecimal> values) {
            addCriterion("losses_amount not in", values, "lossesAmount");
            return (Criteria) this;
        }

        public Criteria andLossesAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("losses_amount between", value1, value2, "lossesAmount");
            return (Criteria) this;
        }

        public Criteria andLossesAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("losses_amount not between", value1, value2, "lossesAmount");
            return (Criteria) this;
        }

        public Criteria andLossesDateIsNull() {
            addCriterion("losses_date is null");
            return (Criteria) this;
        }

        public Criteria andLossesDateIsNotNull() {
            addCriterion("losses_date is not null");
            return (Criteria) this;
        }

        public Criteria andLossesDateEqualTo(Date value) {
            addCriterionForJDBCDate("losses_date =", value, "lossesDate");
            return (Criteria) this;
        }

        public Criteria andLossesDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("losses_date <>", value, "lossesDate");
            return (Criteria) this;
        }

        public Criteria andLossesDateGreaterThan(Date value) {
            addCriterionForJDBCDate("losses_date >", value, "lossesDate");
            return (Criteria) this;
        }

        public Criteria andLossesDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("losses_date >=", value, "lossesDate");
            return (Criteria) this;
        }

        public Criteria andLossesDateLessThan(Date value) {
            addCriterionForJDBCDate("losses_date <", value, "lossesDate");
            return (Criteria) this;
        }

        public Criteria andLossesDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("losses_date <=", value, "lossesDate");
            return (Criteria) this;
        }

        public Criteria andLossesDateIn(List<Date> values) {
            addCriterionForJDBCDate("losses_date in", values, "lossesDate");
            return (Criteria) this;
        }

        public Criteria andLossesDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("losses_date not in", values, "lossesDate");
            return (Criteria) this;
        }

        public Criteria andLossesDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("losses_date between", value1, value2, "lossesDate");
            return (Criteria) this;
        }

        public Criteria andLossesDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("losses_date not between", value1, value2, "lossesDate");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdIsNull() {
            addCriterion("payee_member_id is null");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdIsNotNull() {
            addCriterion("payee_member_id is not null");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdEqualTo(String value) {
            addCriterion("payee_member_id =", value, "payeeMemberId");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdNotEqualTo(String value) {
            addCriterion("payee_member_id <>", value, "payeeMemberId");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdGreaterThan(String value) {
            addCriterion("payee_member_id >", value, "payeeMemberId");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdGreaterThanOrEqualTo(String value) {
            addCriterion("payee_member_id >=", value, "payeeMemberId");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdLessThan(String value) {
            addCriterion("payee_member_id <", value, "payeeMemberId");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdLessThanOrEqualTo(String value) {
            addCriterion("payee_member_id <=", value, "payeeMemberId");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdLike(String value) {
            addCriterion("payee_member_id like", value, "payeeMemberId");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdNotLike(String value) {
            addCriterion("payee_member_id not like", value, "payeeMemberId");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdIn(List<String> values) {
            addCriterion("payee_member_id in", values, "payeeMemberId");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdNotIn(List<String> values) {
            addCriterion("payee_member_id not in", values, "payeeMemberId");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdBetween(String value1, String value2) {
            addCriterion("payee_member_id between", value1, value2, "payeeMemberId");
            return (Criteria) this;
        }

        public Criteria andPayeeMemberIdNotBetween(String value1, String value2) {
            addCriterion("payee_member_id not between", value1, value2, "payeeMemberId");
            return (Criteria) this;
        }

        public Criteria andPayeeNameIsNull() {
            addCriterion("payee_name is null");
            return (Criteria) this;
        }

        public Criteria andPayeeNameIsNotNull() {
            addCriterion("payee_name is not null");
            return (Criteria) this;
        }

        public Criteria andPayeeNameEqualTo(String value) {
            addCriterion("payee_name =", value, "payeeName");
            return (Criteria) this;
        }

        public Criteria andPayeeNameNotEqualTo(String value) {
            addCriterion("payee_name <>", value, "payeeName");
            return (Criteria) this;
        }

        public Criteria andPayeeNameGreaterThan(String value) {
            addCriterion("payee_name >", value, "payeeName");
            return (Criteria) this;
        }

        public Criteria andPayeeNameGreaterThanOrEqualTo(String value) {
            addCriterion("payee_name >=", value, "payeeName");
            return (Criteria) this;
        }

        public Criteria andPayeeNameLessThan(String value) {
            addCriterion("payee_name <", value, "payeeName");
            return (Criteria) this;
        }

        public Criteria andPayeeNameLessThanOrEqualTo(String value) {
            addCriterion("payee_name <=", value, "payeeName");
            return (Criteria) this;
        }

        public Criteria andPayeeNameLike(String value) {
            addCriterion("payee_name like", value, "payeeName");
            return (Criteria) this;
        }

        public Criteria andPayeeNameNotLike(String value) {
            addCriterion("payee_name not like", value, "payeeName");
            return (Criteria) this;
        }

        public Criteria andPayeeNameIn(List<String> values) {
            addCriterion("payee_name in", values, "payeeName");
            return (Criteria) this;
        }

        public Criteria andPayeeNameNotIn(List<String> values) {
            addCriterion("payee_name not in", values, "payeeName");
            return (Criteria) this;
        }

        public Criteria andPayeeNameBetween(String value1, String value2) {
            addCriterion("payee_name between", value1, value2, "payeeName");
            return (Criteria) this;
        }

        public Criteria andPayeeNameNotBetween(String value1, String value2) {
            addCriterion("payee_name not between", value1, value2, "payeeName");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdIsNull() {
            addCriterion("payer_member_id is null");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdIsNotNull() {
            addCriterion("payer_member_id is not null");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdEqualTo(String value) {
            addCriterion("payer_member_id =", value, "payerMemberId");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdNotEqualTo(String value) {
            addCriterion("payer_member_id <>", value, "payerMemberId");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdGreaterThan(String value) {
            addCriterion("payer_member_id >", value, "payerMemberId");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdGreaterThanOrEqualTo(String value) {
            addCriterion("payer_member_id >=", value, "payerMemberId");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdLessThan(String value) {
            addCriterion("payer_member_id <", value, "payerMemberId");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdLessThanOrEqualTo(String value) {
            addCriterion("payer_member_id <=", value, "payerMemberId");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdLike(String value) {
            addCriterion("payer_member_id like", value, "payerMemberId");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdNotLike(String value) {
            addCriterion("payer_member_id not like", value, "payerMemberId");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdIn(List<String> values) {
            addCriterion("payer_member_id in", values, "payerMemberId");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdNotIn(List<String> values) {
            addCriterion("payer_member_id not in", values, "payerMemberId");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdBetween(String value1, String value2) {
            addCriterion("payer_member_id between", value1, value2, "payerMemberId");
            return (Criteria) this;
        }

        public Criteria andPayerMemberIdNotBetween(String value1, String value2) {
            addCriterion("payer_member_id not between", value1, value2, "payerMemberId");
            return (Criteria) this;
        }

        public Criteria andPayerNameIsNull() {
            addCriterion("payer_name is null");
            return (Criteria) this;
        }

        public Criteria andPayerNameIsNotNull() {
            addCriterion("payer_name is not null");
            return (Criteria) this;
        }

        public Criteria andPayerNameEqualTo(String value) {
            addCriterion("payer_name =", value, "payerName");
            return (Criteria) this;
        }

        public Criteria andPayerNameNotEqualTo(String value) {
            addCriterion("payer_name <>", value, "payerName");
            return (Criteria) this;
        }

        public Criteria andPayerNameGreaterThan(String value) {
            addCriterion("payer_name >", value, "payerName");
            return (Criteria) this;
        }

        public Criteria andPayerNameGreaterThanOrEqualTo(String value) {
            addCriterion("payer_name >=", value, "payerName");
            return (Criteria) this;
        }

        public Criteria andPayerNameLessThan(String value) {
            addCriterion("payer_name <", value, "payerName");
            return (Criteria) this;
        }

        public Criteria andPayerNameLessThanOrEqualTo(String value) {
            addCriterion("payer_name <=", value, "payerName");
            return (Criteria) this;
        }

        public Criteria andPayerNameLike(String value) {
            addCriterion("payer_name like", value, "payerName");
            return (Criteria) this;
        }

        public Criteria andPayerNameNotLike(String value) {
            addCriterion("payer_name not like", value, "payerName");
            return (Criteria) this;
        }

        public Criteria andPayerNameIn(List<String> values) {
            addCriterion("payer_name in", values, "payerName");
            return (Criteria) this;
        }

        public Criteria andPayerNameNotIn(List<String> values) {
            addCriterion("payer_name not in", values, "payerName");
            return (Criteria) this;
        }

        public Criteria andPayerNameBetween(String value1, String value2) {
            addCriterion("payer_name between", value1, value2, "payerName");
            return (Criteria) this;
        }

        public Criteria andPayerNameNotBetween(String value1, String value2) {
            addCriterion("payer_name not between", value1, value2, "payerName");
            return (Criteria) this;
        }

        public Criteria andPaymentModeIsNull() {
            addCriterion("payment_mode is null");
            return (Criteria) this;
        }

        public Criteria andPaymentModeIsNotNull() {
            addCriterion("payment_mode is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentModeEqualTo(Byte value) {
            addCriterion("payment_mode =", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeNotEqualTo(Byte value) {
            addCriterion("payment_mode <>", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeGreaterThan(Byte value) {
            addCriterion("payment_mode >", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeGreaterThanOrEqualTo(Byte value) {
            addCriterion("payment_mode >=", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeLessThan(Byte value) {
            addCriterion("payment_mode <", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeLessThanOrEqualTo(Byte value) {
            addCriterion("payment_mode <=", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeIn(List<Byte> values) {
            addCriterion("payment_mode in", values, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeNotIn(List<Byte> values) {
            addCriterion("payment_mode not in", values, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeBetween(Byte value1, Byte value2) {
            addCriterion("payment_mode between", value1, value2, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeNotBetween(Byte value1, Byte value2) {
            addCriterion("payment_mode not between", value1, value2, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceIsNull() {
            addCriterion("is_auto_balance is null");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceIsNotNull() {
            addCriterion("is_auto_balance is not null");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceEqualTo(String value) {
            addCriterion("is_auto_balance =", value, "isAutoBalance");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceNotEqualTo(String value) {
            addCriterion("is_auto_balance <>", value, "isAutoBalance");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceGreaterThan(String value) {
            addCriterion("is_auto_balance >", value, "isAutoBalance");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceGreaterThanOrEqualTo(String value) {
            addCriterion("is_auto_balance >=", value, "isAutoBalance");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceLessThan(String value) {
            addCriterion("is_auto_balance <", value, "isAutoBalance");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceLessThanOrEqualTo(String value) {
            addCriterion("is_auto_balance <=", value, "isAutoBalance");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceLike(String value) {
            addCriterion("is_auto_balance like", value, "isAutoBalance");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceNotLike(String value) {
            addCriterion("is_auto_balance not like", value, "isAutoBalance");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceIn(List<String> values) {
            addCriterion("is_auto_balance in", values, "isAutoBalance");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceNotIn(List<String> values) {
            addCriterion("is_auto_balance not in", values, "isAutoBalance");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceBetween(String value1, String value2) {
            addCriterion("is_auto_balance between", value1, value2, "isAutoBalance");
            return (Criteria) this;
        }

        public Criteria andIsAutoBalanceNotBetween(String value1, String value2) {
            addCriterion("is_auto_balance not between", value1, value2, "isAutoBalance");
            return (Criteria) this;
        }

        public Criteria andIsImmediatelyBalanceIsNull() {
            addCriterion("is_immediately_balance is null");
            return (Criteria) this;
        }

        public Criteria andIsImmediatelyBalanceIsNotNull() {
            addCriterion("is_immediately_balance is not null");
            return (Criteria) this;
        }

        public Criteria andIsImmediatelyBalanceEqualTo(Boolean value) {
            addCriterion("is_immediately_balance =", value, "isImmediatelyBalance");
            return (Criteria) this;
        }

        public Criteria andIsImmediatelyBalanceNotEqualTo(Boolean value) {
            addCriterion("is_immediately_balance <>", value, "isImmediatelyBalance");
            return (Criteria) this;
        }

        public Criteria andIsImmediatelyBalanceGreaterThan(Boolean value) {
            addCriterion("is_immediately_balance >", value, "isImmediatelyBalance");
            return (Criteria) this;
        }

        public Criteria andIsImmediatelyBalanceGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_immediately_balance >=", value, "isImmediatelyBalance");
            return (Criteria) this;
        }

        public Criteria andIsImmediatelyBalanceLessThan(Boolean value) {
            addCriterion("is_immediately_balance <", value, "isImmediatelyBalance");
            return (Criteria) this;
        }

        public Criteria andIsImmediatelyBalanceLessThanOrEqualTo(Boolean value) {
            addCriterion("is_immediately_balance <=", value, "isImmediatelyBalance");
            return (Criteria) this;
        }

        public Criteria andIsImmediatelyBalanceIn(List<Boolean> values) {
            addCriterion("is_immediately_balance in", values, "isImmediatelyBalance");
            return (Criteria) this;
        }

        public Criteria andIsImmediatelyBalanceNotIn(List<Boolean> values) {
            addCriterion("is_immediately_balance not in", values, "isImmediatelyBalance");
            return (Criteria) this;
        }

        public Criteria andIsImmediatelyBalanceBetween(Boolean value1, Boolean value2) {
            addCriterion("is_immediately_balance between", value1, value2, "isImmediatelyBalance");
            return (Criteria) this;
        }

        public Criteria andIsImmediatelyBalanceNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_immediately_balance not between", value1, value2, "isImmediatelyBalance");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdIsNull() {
            addCriterion("trade_bill_id is null");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdIsNotNull() {
            addCriterion("trade_bill_id is not null");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdEqualTo(String value) {
            addCriterion("trade_bill_id =", value, "tradeBillId");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdNotEqualTo(String value) {
            addCriterion("trade_bill_id <>", value, "tradeBillId");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdGreaterThan(String value) {
            addCriterion("trade_bill_id >", value, "tradeBillId");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdGreaterThanOrEqualTo(String value) {
            addCriterion("trade_bill_id >=", value, "tradeBillId");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdLessThan(String value) {
            addCriterion("trade_bill_id <", value, "tradeBillId");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdLessThanOrEqualTo(String value) {
            addCriterion("trade_bill_id <=", value, "tradeBillId");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdLike(String value) {
            addCriterion("trade_bill_id like", value, "tradeBillId");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdNotLike(String value) {
            addCriterion("trade_bill_id not like", value, "tradeBillId");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdIn(List<String> values) {
            addCriterion("trade_bill_id in", values, "tradeBillId");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdNotIn(List<String> values) {
            addCriterion("trade_bill_id not in", values, "tradeBillId");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdBetween(String value1, String value2) {
            addCriterion("trade_bill_id between", value1, value2, "tradeBillId");
            return (Criteria) this;
        }

        public Criteria andTradeBillIdNotBetween(String value1, String value2) {
            addCriterion("trade_bill_id not between", value1, value2, "tradeBillId");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoIsNull() {
            addCriterion("trade_bill_no is null");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoIsNotNull() {
            addCriterion("trade_bill_no is not null");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoEqualTo(String value) {
            addCriterion("trade_bill_no =", value, "tradeBillNo");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoNotEqualTo(String value) {
            addCriterion("trade_bill_no <>", value, "tradeBillNo");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoGreaterThan(String value) {
            addCriterion("trade_bill_no >", value, "tradeBillNo");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoGreaterThanOrEqualTo(String value) {
            addCriterion("trade_bill_no >=", value, "tradeBillNo");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoLessThan(String value) {
            addCriterion("trade_bill_no <", value, "tradeBillNo");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoLessThanOrEqualTo(String value) {
            addCriterion("trade_bill_no <=", value, "tradeBillNo");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoLike(String value) {
            addCriterion("trade_bill_no like", value, "tradeBillNo");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoNotLike(String value) {
            addCriterion("trade_bill_no not like", value, "tradeBillNo");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoIn(List<String> values) {
            addCriterion("trade_bill_no in", values, "tradeBillNo");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoNotIn(List<String> values) {
            addCriterion("trade_bill_no not in", values, "tradeBillNo");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoBetween(String value1, String value2) {
            addCriterion("trade_bill_no between", value1, value2, "tradeBillNo");
            return (Criteria) this;
        }

        public Criteria andTradeBillNoNotBetween(String value1, String value2) {
            addCriterion("trade_bill_no not between", value1, value2, "tradeBillNo");
            return (Criteria) this;
        }

        public Criteria andTradeBillTypeIsNull() {
            addCriterion("trade_bill_type is null");
            return (Criteria) this;
        }

        public Criteria andTradeBillTypeIsNotNull() {
            addCriterion("trade_bill_type is not null");
            return (Criteria) this;
        }

        public Criteria andTradeBillTypeEqualTo(Byte value) {
            addCriterion("trade_bill_type =", value, "tradeBillType");
            return (Criteria) this;
        }

        public Criteria andTradeBillTypeNotEqualTo(Byte value) {
            addCriterion("trade_bill_type <>", value, "tradeBillType");
            return (Criteria) this;
        }

        public Criteria andTradeBillTypeGreaterThan(Byte value) {
            addCriterion("trade_bill_type >", value, "tradeBillType");
            return (Criteria) this;
        }

        public Criteria andTradeBillTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("trade_bill_type >=", value, "tradeBillType");
            return (Criteria) this;
        }

        public Criteria andTradeBillTypeLessThan(Byte value) {
            addCriterion("trade_bill_type <", value, "tradeBillType");
            return (Criteria) this;
        }

        public Criteria andTradeBillTypeLessThanOrEqualTo(Byte value) {
            addCriterion("trade_bill_type <=", value, "tradeBillType");
            return (Criteria) this;
        }

        public Criteria andTradeBillTypeIn(List<Byte> values) {
            addCriterion("trade_bill_type in", values, "tradeBillType");
            return (Criteria) this;
        }

        public Criteria andTradeBillTypeNotIn(List<Byte> values) {
            addCriterion("trade_bill_type not in", values, "tradeBillType");
            return (Criteria) this;
        }

        public Criteria andTradeBillTypeBetween(Byte value1, Byte value2) {
            addCriterion("trade_bill_type between", value1, value2, "tradeBillType");
            return (Criteria) this;
        }

        public Criteria andTradeBillTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("trade_bill_type not between", value1, value2, "tradeBillType");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdIsNull() {
            addCriterion("original_way_bill_id is null");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdIsNotNull() {
            addCriterion("original_way_bill_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdEqualTo(String value) {
            addCriterion("original_way_bill_id =", value, "originalWayBillId");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdNotEqualTo(String value) {
            addCriterion("original_way_bill_id <>", value, "originalWayBillId");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdGreaterThan(String value) {
            addCriterion("original_way_bill_id >", value, "originalWayBillId");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdGreaterThanOrEqualTo(String value) {
            addCriterion("original_way_bill_id >=", value, "originalWayBillId");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdLessThan(String value) {
            addCriterion("original_way_bill_id <", value, "originalWayBillId");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdLessThanOrEqualTo(String value) {
            addCriterion("original_way_bill_id <=", value, "originalWayBillId");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdLike(String value) {
            addCriterion("original_way_bill_id like", value, "originalWayBillId");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdNotLike(String value) {
            addCriterion("original_way_bill_id not like", value, "originalWayBillId");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdIn(List<String> values) {
            addCriterion("original_way_bill_id in", values, "originalWayBillId");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdNotIn(List<String> values) {
            addCriterion("original_way_bill_id not in", values, "originalWayBillId");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdBetween(String value1, String value2) {
            addCriterion("original_way_bill_id between", value1, value2, "originalWayBillId");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillIdNotBetween(String value1, String value2) {
            addCriterion("original_way_bill_id not between", value1, value2, "originalWayBillId");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillIsNull() {
            addCriterion("is_supplement_bill is null");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillIsNotNull() {
            addCriterion("is_supplement_bill is not null");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillEqualTo(String value) {
            addCriterion("is_supplement_bill =", value, "isSupplementBill");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillNotEqualTo(String value) {
            addCriterion("is_supplement_bill <>", value, "isSupplementBill");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillGreaterThan(String value) {
            addCriterion("is_supplement_bill >", value, "isSupplementBill");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillGreaterThanOrEqualTo(String value) {
            addCriterion("is_supplement_bill >=", value, "isSupplementBill");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillLessThan(String value) {
            addCriterion("is_supplement_bill <", value, "isSupplementBill");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillLessThanOrEqualTo(String value) {
            addCriterion("is_supplement_bill <=", value, "isSupplementBill");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillLike(String value) {
            addCriterion("is_supplement_bill like", value, "isSupplementBill");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillNotLike(String value) {
            addCriterion("is_supplement_bill not like", value, "isSupplementBill");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillIn(List<String> values) {
            addCriterion("is_supplement_bill in", values, "isSupplementBill");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillNotIn(List<String> values) {
            addCriterion("is_supplement_bill not in", values, "isSupplementBill");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillBetween(String value1, String value2) {
            addCriterion("is_supplement_bill between", value1, value2, "isSupplementBill");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBillNotBetween(String value1, String value2) {
            addCriterion("is_supplement_bill not between", value1, value2, "isSupplementBill");
            return (Criteria) this;
        }

        public Criteria andIsMonthSettleIsNull() {
            addCriterion("is_month_settle is null");
            return (Criteria) this;
        }

        public Criteria andIsMonthSettleIsNotNull() {
            addCriterion("is_month_settle is not null");
            return (Criteria) this;
        }

        public Criteria andIsMonthSettleEqualTo(Boolean value) {
            addCriterion("is_month_settle =", value, "isMonthSettle");
            return (Criteria) this;
        }

        public Criteria andIsMonthSettleNotEqualTo(Boolean value) {
            addCriterion("is_month_settle <>", value, "isMonthSettle");
            return (Criteria) this;
        }

        public Criteria andIsMonthSettleGreaterThan(Boolean value) {
            addCriterion("is_month_settle >", value, "isMonthSettle");
            return (Criteria) this;
        }

        public Criteria andIsMonthSettleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_month_settle >=", value, "isMonthSettle");
            return (Criteria) this;
        }

        public Criteria andIsMonthSettleLessThan(Boolean value) {
            addCriterion("is_month_settle <", value, "isMonthSettle");
            return (Criteria) this;
        }

        public Criteria andIsMonthSettleLessThanOrEqualTo(Boolean value) {
            addCriterion("is_month_settle <=", value, "isMonthSettle");
            return (Criteria) this;
        }

        public Criteria andIsMonthSettleIn(List<Boolean> values) {
            addCriterion("is_month_settle in", values, "isMonthSettle");
            return (Criteria) this;
        }

        public Criteria andIsMonthSettleNotIn(List<Boolean> values) {
            addCriterion("is_month_settle not in", values, "isMonthSettle");
            return (Criteria) this;
        }

        public Criteria andIsMonthSettleBetween(Boolean value1, Boolean value2) {
            addCriterion("is_month_settle between", value1, value2, "isMonthSettle");
            return (Criteria) this;
        }

        public Criteria andIsMonthSettleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_month_settle not between", value1, value2, "isMonthSettle");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNull() {
            addCriterion("delete_flg is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNotNull() {
            addCriterion("delete_flg is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgEqualTo(String value) {
            addCriterion("delete_flg =", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotEqualTo(String value) {
            addCriterion("delete_flg <>", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThan(String value) {
            addCriterion("delete_flg >", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThanOrEqualTo(String value) {
            addCriterion("delete_flg >=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThan(String value) {
            addCriterion("delete_flg <", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThanOrEqualTo(String value) {
            addCriterion("delete_flg <=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLike(String value) {
            addCriterion("delete_flg like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotLike(String value) {
            addCriterion("delete_flg not like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIn(List<String> values) {
            addCriterion("delete_flg in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotIn(List<String> values) {
            addCriterion("delete_flg not in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgBetween(String value1, String value2) {
            addCriterion("delete_flg between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotBetween(String value1, String value2) {
            addCriterion("delete_flg not between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andCreaterIdIsNull() {
            addCriterion("creater_id is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIdIsNotNull() {
            addCriterion("creater_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterIdEqualTo(String value) {
            addCriterion("creater_id =", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotEqualTo(String value) {
            addCriterion("creater_id <>", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdGreaterThan(String value) {
            addCriterion("creater_id >", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdGreaterThanOrEqualTo(String value) {
            addCriterion("creater_id >=", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdLessThan(String value) {
            addCriterion("creater_id <", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdLessThanOrEqualTo(String value) {
            addCriterion("creater_id <=", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdLike(String value) {
            addCriterion("creater_id like", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotLike(String value) {
            addCriterion("creater_id not like", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdIn(List<String> values) {
            addCriterion("creater_id in", values, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotIn(List<String> values) {
            addCriterion("creater_id not in", values, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdBetween(String value1, String value2) {
            addCriterion("creater_id between", value1, value2, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotBetween(String value1, String value2) {
            addCriterion("creater_id not between", value1, value2, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdIsNull() {
            addCriterion("updater_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdIsNotNull() {
            addCriterion("updater_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdEqualTo(String value) {
            addCriterion("updater_id =", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdNotEqualTo(String value) {
            addCriterion("updater_id <>", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdGreaterThan(String value) {
            addCriterion("updater_id >", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdGreaterThanOrEqualTo(String value) {
            addCriterion("updater_id >=", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdLessThan(String value) {
            addCriterion("updater_id <", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdLessThanOrEqualTo(String value) {
            addCriterion("updater_id <=", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdLike(String value) {
            addCriterion("updater_id like", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdNotLike(String value) {
            addCriterion("updater_id not like", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdIn(List<String> values) {
            addCriterion("updater_id in", values, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdNotIn(List<String> values) {
            addCriterion("updater_id not in", values, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdBetween(String value1, String value2) {
            addCriterion("updater_id between", value1, value2, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdNotBetween(String value1, String value2) {
            addCriterion("updater_id not between", value1, value2, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andTradeBillCreateTimeIsNull() {
            addCriterion("trade_bill_create_time is null");
            return (Criteria) this;
        }

        public Criteria andTradeBillCreateTimeIsNotNull() {
            addCriterion("trade_bill_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andTradeBillCreateTimeEqualTo(Date value) {
            addCriterion("trade_bill_create_time =", value, "tradeBillCreateTime");
            return (Criteria) this;
        }

        public Criteria andTradeBillCreateTimeNotEqualTo(Date value) {
            addCriterion("trade_bill_create_time <>", value, "tradeBillCreateTime");
            return (Criteria) this;
        }

        public Criteria andTradeBillCreateTimeGreaterThan(Date value) {
            addCriterion("trade_bill_create_time >", value, "tradeBillCreateTime");
            return (Criteria) this;
        }

        public Criteria andTradeBillCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("trade_bill_create_time >=", value, "tradeBillCreateTime");
            return (Criteria) this;
        }

        public Criteria andTradeBillCreateTimeLessThan(Date value) {
            addCriterion("trade_bill_create_time <", value, "tradeBillCreateTime");
            return (Criteria) this;
        }

        public Criteria andTradeBillCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("trade_bill_create_time <=", value, "tradeBillCreateTime");
            return (Criteria) this;
        }

        public Criteria andTradeBillCreateTimeIn(List<Date> values) {
            addCriterion("trade_bill_create_time in", values, "tradeBillCreateTime");
            return (Criteria) this;
        }

        public Criteria andTradeBillCreateTimeNotIn(List<Date> values) {
            addCriterion("trade_bill_create_time not in", values, "tradeBillCreateTime");
            return (Criteria) this;
        }

        public Criteria andTradeBillCreateTimeBetween(Date value1, Date value2) {
            addCriterion("trade_bill_create_time between", value1, value2, "tradeBillCreateTime");
            return (Criteria) this;
        }

        public Criteria andTradeBillCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("trade_bill_create_time not between", value1, value2, "tradeBillCreateTime");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoIsNull() {
            addCriterion("original_way_bill_no is null");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoIsNotNull() {
            addCriterion("original_way_bill_no is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoEqualTo(String value) {
            addCriterion("original_way_bill_no =", value, "originalWayBillNo");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoNotEqualTo(String value) {
            addCriterion("original_way_bill_no <>", value, "originalWayBillNo");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoGreaterThan(String value) {
            addCriterion("original_way_bill_no >", value, "originalWayBillNo");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoGreaterThanOrEqualTo(String value) {
            addCriterion("original_way_bill_no >=", value, "originalWayBillNo");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoLessThan(String value) {
            addCriterion("original_way_bill_no <", value, "originalWayBillNo");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoLessThanOrEqualTo(String value) {
            addCriterion("original_way_bill_no <=", value, "originalWayBillNo");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoLike(String value) {
            addCriterion("original_way_bill_no like", value, "originalWayBillNo");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoNotLike(String value) {
            addCriterion("original_way_bill_no not like", value, "originalWayBillNo");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoIn(List<String> values) {
            addCriterion("original_way_bill_no in", values, "originalWayBillNo");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoNotIn(List<String> values) {
            addCriterion("original_way_bill_no not in", values, "originalWayBillNo");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoBetween(String value1, String value2) {
            addCriterion("original_way_bill_no between", value1, value2, "originalWayBillNo");
            return (Criteria) this;
        }

        public Criteria andOriginalWayBillNoNotBetween(String value1, String value2) {
            addCriterion("original_way_bill_no not between", value1, value2, "originalWayBillNo");
            return (Criteria) this;
        }

        public Criteria andLatestTimeIsNull() {
            addCriterion("latest_time is null");
            return (Criteria) this;
        }

        public Criteria andLatestTimeIsNotNull() {
            addCriterion("latest_time is not null");
            return (Criteria) this;
        }

        public Criteria andLatestTimeEqualTo(Date value) {
            addCriterion("latest_time =", value, "latestTime");
            return (Criteria) this;
        }

        public Criteria andLatestTimeNotEqualTo(Date value) {
            addCriterion("latest_time <>", value, "latestTime");
            return (Criteria) this;
        }

        public Criteria andLatestTimeGreaterThan(Date value) {
            addCriterion("latest_time >", value, "latestTime");
            return (Criteria) this;
        }

        public Criteria andLatestTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("latest_time >=", value, "latestTime");
            return (Criteria) this;
        }

        public Criteria andLatestTimeLessThan(Date value) {
            addCriterion("latest_time <", value, "latestTime");
            return (Criteria) this;
        }

        public Criteria andLatestTimeLessThanOrEqualTo(Date value) {
            addCriterion("latest_time <=", value, "latestTime");
            return (Criteria) this;
        }

        public Criteria andLatestTimeIn(List<Date> values) {
            addCriterion("latest_time in", values, "latestTime");
            return (Criteria) this;
        }

        public Criteria andLatestTimeNotIn(List<Date> values) {
            addCriterion("latest_time not in", values, "latestTime");
            return (Criteria) this;
        }

        public Criteria andLatestTimeBetween(Date value1, Date value2) {
            addCriterion("latest_time between", value1, value2, "latestTime");
            return (Criteria) this;
        }

        public Criteria andLatestTimeNotBetween(Date value1, Date value2) {
            addCriterion("latest_time not between", value1, value2, "latestTime");
            return (Criteria) this;
        }

        public Criteria andPayeeBalanceStatusIsNull() {
            addCriterion("payee_balance_status is null");
            return (Criteria) this;
        }

        public Criteria andPayeeBalanceStatusIsNotNull() {
            addCriterion("payee_balance_status is not null");
            return (Criteria) this;
        }

        public Criteria andPayeeBalanceStatusEqualTo(Byte value) {
            addCriterion("payee_balance_status =", value, "payeeBalanceStatus");
            return (Criteria) this;
        }

        public Criteria andPayeeBalanceStatusNotEqualTo(Byte value) {
            addCriterion("payee_balance_status <>", value, "payeeBalanceStatus");
            return (Criteria) this;
        }

        public Criteria andPayeeBalanceStatusGreaterThan(Byte value) {
            addCriterion("payee_balance_status >", value, "payeeBalanceStatus");
            return (Criteria) this;
        }

        public Criteria andPayeeBalanceStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("payee_balance_status >=", value, "payeeBalanceStatus");
            return (Criteria) this;
        }

        public Criteria andPayeeBalanceStatusLessThan(Byte value) {
            addCriterion("payee_balance_status <", value, "payeeBalanceStatus");
            return (Criteria) this;
        }

        public Criteria andPayeeBalanceStatusLessThanOrEqualTo(Byte value) {
            addCriterion("payee_balance_status <=", value, "payeeBalanceStatus");
            return (Criteria) this;
        }

        public Criteria andPayeeBalanceStatusIn(List<Byte> values) {
            addCriterion("payee_balance_status in", values, "payeeBalanceStatus");
            return (Criteria) this;
        }

        public Criteria andPayeeBalanceStatusNotIn(List<Byte> values) {
            addCriterion("payee_balance_status not in", values, "payeeBalanceStatus");
            return (Criteria) this;
        }

        public Criteria andPayeeBalanceStatusBetween(Byte value1, Byte value2) {
            addCriterion("payee_balance_status between", value1, value2, "payeeBalanceStatus");
            return (Criteria) this;
        }

        public Criteria andPayeeBalanceStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("payee_balance_status not between", value1, value2, "payeeBalanceStatus");
            return (Criteria) this;
        }

        public Criteria andAlreadyIncomeAmountIsNull() {
            addCriterion("already_income_amount is null");
            return (Criteria) this;
        }

        public Criteria andAlreadyIncomeAmountIsNotNull() {
            addCriterion("already_income_amount is not null");
            return (Criteria) this;
        }

        public Criteria andAlreadyIncomeAmountEqualTo(BigDecimal value) {
            addCriterion("already_income_amount =", value, "alreadyIncomeAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyIncomeAmountNotEqualTo(BigDecimal value) {
            addCriterion("already_income_amount <>", value, "alreadyIncomeAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyIncomeAmountGreaterThan(BigDecimal value) {
            addCriterion("already_income_amount >", value, "alreadyIncomeAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyIncomeAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("already_income_amount >=", value, "alreadyIncomeAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyIncomeAmountLessThan(BigDecimal value) {
            addCriterion("already_income_amount <", value, "alreadyIncomeAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyIncomeAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("already_income_amount <=", value, "alreadyIncomeAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyIncomeAmountIn(List<BigDecimal> values) {
            addCriterion("already_income_amount in", values, "alreadyIncomeAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyIncomeAmountNotIn(List<BigDecimal> values) {
            addCriterion("already_income_amount not in", values, "alreadyIncomeAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyIncomeAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("already_income_amount between", value1, value2, "alreadyIncomeAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyIncomeAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("already_income_amount not between", value1, value2, "alreadyIncomeAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyPayAmountIsNull() {
            addCriterion("already_pay_amount is null");
            return (Criteria) this;
        }

        public Criteria andAlreadyPayAmountIsNotNull() {
            addCriterion("already_pay_amount is not null");
            return (Criteria) this;
        }

        public Criteria andAlreadyPayAmountEqualTo(BigDecimal value) {
            addCriterion("already_pay_amount =", value, "alreadyPayAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyPayAmountNotEqualTo(BigDecimal value) {
            addCriterion("already_pay_amount <>", value, "alreadyPayAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyPayAmountGreaterThan(BigDecimal value) {
            addCriterion("already_pay_amount >", value, "alreadyPayAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyPayAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("already_pay_amount >=", value, "alreadyPayAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyPayAmountLessThan(BigDecimal value) {
            addCriterion("already_pay_amount <", value, "alreadyPayAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyPayAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("already_pay_amount <=", value, "alreadyPayAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyPayAmountIn(List<BigDecimal> values) {
            addCriterion("already_pay_amount in", values, "alreadyPayAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyPayAmountNotIn(List<BigDecimal> values) {
            addCriterion("already_pay_amount not in", values, "alreadyPayAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyPayAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("already_pay_amount between", value1, value2, "alreadyPayAmount");
            return (Criteria) this;
        }

        public Criteria andAlreadyPayAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("already_pay_amount not between", value1, value2, "alreadyPayAmount");
            return (Criteria) this;
        }

        public Criteria andLossesStatusIsNull() {
            addCriterion("losses_status is null");
            return (Criteria) this;
        }

        public Criteria andLossesStatusIsNotNull() {
            addCriterion("losses_status is not null");
            return (Criteria) this;
        }

        public Criteria andLossesStatusEqualTo(Byte value) {
            addCriterion("losses_status =", value, "lossesStatus");
            return (Criteria) this;
        }

        public Criteria andLossesStatusNotEqualTo(Byte value) {
            addCriterion("losses_status <>", value, "lossesStatus");
            return (Criteria) this;
        }

        public Criteria andLossesStatusGreaterThan(Byte value) {
            addCriterion("losses_status >", value, "lossesStatus");
            return (Criteria) this;
        }

        public Criteria andLossesStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("losses_status >=", value, "lossesStatus");
            return (Criteria) this;
        }

        public Criteria andLossesStatusLessThan(Byte value) {
            addCriterion("losses_status <", value, "lossesStatus");
            return (Criteria) this;
        }

        public Criteria andLossesStatusLessThanOrEqualTo(Byte value) {
            addCriterion("losses_status <=", value, "lossesStatus");
            return (Criteria) this;
        }

        public Criteria andLossesStatusIn(List<Byte> values) {
            addCriterion("losses_status in", values, "lossesStatus");
            return (Criteria) this;
        }

        public Criteria andLossesStatusNotIn(List<Byte> values) {
            addCriterion("losses_status not in", values, "lossesStatus");
            return (Criteria) this;
        }

        public Criteria andLossesStatusBetween(Byte value1, Byte value2) {
            addCriterion("losses_status between", value1, value2, "lossesStatus");
            return (Criteria) this;
        }

        public Criteria andLossesStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("losses_status not between", value1, value2, "lossesStatus");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdIsNull() {
            addCriterion("original_fee_id is null");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdIsNotNull() {
            addCriterion("original_fee_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdEqualTo(String value) {
            addCriterion("original_fee_id =", value, "originalFeeId");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdNotEqualTo(String value) {
            addCriterion("original_fee_id <>", value, "originalFeeId");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdGreaterThan(String value) {
            addCriterion("original_fee_id >", value, "originalFeeId");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdGreaterThanOrEqualTo(String value) {
            addCriterion("original_fee_id >=", value, "originalFeeId");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdLessThan(String value) {
            addCriterion("original_fee_id <", value, "originalFeeId");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdLessThanOrEqualTo(String value) {
            addCriterion("original_fee_id <=", value, "originalFeeId");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdLike(String value) {
            addCriterion("original_fee_id like", value, "originalFeeId");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdNotLike(String value) {
            addCriterion("original_fee_id not like", value, "originalFeeId");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdIn(List<String> values) {
            addCriterion("original_fee_id in", values, "originalFeeId");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdNotIn(List<String> values) {
            addCriterion("original_fee_id not in", values, "originalFeeId");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdBetween(String value1, String value2) {
            addCriterion("original_fee_id between", value1, value2, "originalFeeId");
            return (Criteria) this;
        }

        public Criteria andOriginalFeeIdNotBetween(String value1, String value2) {
            addCriterion("original_fee_id not between", value1, value2, "originalFeeId");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoIsNull() {
            addCriterion("fee_serial_no is null");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoIsNotNull() {
            addCriterion("fee_serial_no is not null");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoEqualTo(String value) {
            addCriterion("fee_serial_no =", value, "feeSerialNo");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoNotEqualTo(String value) {
            addCriterion("fee_serial_no <>", value, "feeSerialNo");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoGreaterThan(String value) {
            addCriterion("fee_serial_no >", value, "feeSerialNo");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoGreaterThanOrEqualTo(String value) {
            addCriterion("fee_serial_no >=", value, "feeSerialNo");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoLessThan(String value) {
            addCriterion("fee_serial_no <", value, "feeSerialNo");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoLessThanOrEqualTo(String value) {
            addCriterion("fee_serial_no <=", value, "feeSerialNo");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoLike(String value) {
            addCriterion("fee_serial_no like", value, "feeSerialNo");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoNotLike(String value) {
            addCriterion("fee_serial_no not like", value, "feeSerialNo");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoIn(List<String> values) {
            addCriterion("fee_serial_no in", values, "feeSerialNo");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoNotIn(List<String> values) {
            addCriterion("fee_serial_no not in", values, "feeSerialNo");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoBetween(String value1, String value2) {
            addCriterion("fee_serial_no between", value1, value2, "feeSerialNo");
            return (Criteria) this;
        }

        public Criteria andFeeSerialNoNotBetween(String value1, String value2) {
            addCriterion("fee_serial_no not between", value1, value2, "feeSerialNo");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoIsNull() {
            addCriterion("trade_serial_no is null");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoIsNotNull() {
            addCriterion("trade_serial_no is not null");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoEqualTo(String value) {
            addCriterion("trade_serial_no =", value, "tradeSerialNo");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoNotEqualTo(String value) {
            addCriterion("trade_serial_no <>", value, "tradeSerialNo");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoGreaterThan(String value) {
            addCriterion("trade_serial_no >", value, "tradeSerialNo");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoGreaterThanOrEqualTo(String value) {
            addCriterion("trade_serial_no >=", value, "tradeSerialNo");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoLessThan(String value) {
            addCriterion("trade_serial_no <", value, "tradeSerialNo");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoLessThanOrEqualTo(String value) {
            addCriterion("trade_serial_no <=", value, "tradeSerialNo");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoLike(String value) {
            addCriterion("trade_serial_no like", value, "tradeSerialNo");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoNotLike(String value) {
            addCriterion("trade_serial_no not like", value, "tradeSerialNo");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoIn(List<String> values) {
            addCriterion("trade_serial_no in", values, "tradeSerialNo");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoNotIn(List<String> values) {
            addCriterion("trade_serial_no not in", values, "tradeSerialNo");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoBetween(String value1, String value2) {
            addCriterion("trade_serial_no between", value1, value2, "tradeSerialNo");
            return (Criteria) this;
        }

        public Criteria andTradeSerialNoNotBetween(String value1, String value2) {
            addCriterion("trade_serial_no not between", value1, value2, "tradeSerialNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table losses_detail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table losses_detail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}